version: "3.9"
services:
  app-node-service:
    platform: linux/amd64 # Add this line to set the correct platform
    build: .
    ports:
      - "8000:8000"
    environment:
      - .env
      - REDIS_HOST=my-redis-container
      - REDIS_PORT=6379
    depends_on:
      my-redis-container:
        condition: service_healthy
    networks:
      - app_networks

  my-redis-container:
    image: redis:7.4.0
    ports:
      - "6379:6379"
    networks:
      - app_networks
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data:
