version: "3.9"
services:
  app-node-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://avnadmin:AVNS_Ln3_Vked6PepDgbcrJe@pg-23d27e04-ai3n17a75-0a2a.e.aivencloud.com:11465/defaultdb?schema=public
      - EAPI=/api/v1
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - SECRET_KEY=scholarship
      - REFRESH_TOKEN=scholarship__adffdslakdf
      - JWT_TIMEOUT=50h
      - JWT_REFRESH_TIMEOUT=72h
      - AWS_ACCESS_KEY_ID=AKIA5G2VGPJNXWJZ2KNL
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-1
    depends_on:
      my-redis-container:
        condition: service_healthy
    networks:
      - app_networks

  my-redis-container:
    image: redis:7.4.0
    ports:
      - "6379:6379" # Redis default port
    networks:
      - app_networks
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data:
